### PR TITLE
Some more translations

### PR DESCRIPTION
**Pull request by llogiq**
It's been a while since I made a PR, so here are some updates. Cheers!

### CODE REVIEW

**Comment by QilessQi** [comment]
Thanks!

**Comment by llogiq** [comment]
Case 200 was quite a hard nut to crack, because German doesn't have that much one-syllable adjectives.

**Comment by llogiq** [comment]
@QilessQi Are you OK? Or buried under a load of work?

**Comment by QilessQi** [comment]
Both.  :-)   I was travelling out of the country last week, and have come
back to a mountain of work (architectural and coding).  I'm hoping to get
caught up this weekend.

Regards,

Qi

**Comment by QilessQi** [comment]
Merged #365

**Comment by QilessQi** [comment]
Okay, really merged #365 this time.  :-)

**Pull request merged**
