### PR TITLE
Translations Case 97 and 126.

### PR DESCRIPTION
**Pull request by llogiq**
I even managed to make the poem of case 126 rhyme while keeping the spirit of the original. :smile:

### CODE REVIEW

**Comment by alessandro1997** [comment]
Case 126 doesn't contain the Lang and Translator headers. Can you fix it?

**Comment by llogiq** [comment]
Done. Wonder how I missed that.

**Comment by alessandro1997** [comment]
Thanks! :smile:

**Comment by QilessQi** [comment]
Awesome!  :-)

Regards,

Qi

**Pull request merged**
