### PR TITLE
Case 217 - FR - L'oeuf de la Chimère

### PR DESCRIPTION
**Pull request by abelards**

### CODE REVIEW

**Comment by abelards** [comment]
BTW I'm not fond of the new /contents page: less results for a quick glance?
Perhaps make the translations button more obvious, too (just add the label to the icon)?

I get the page could become heavy and overloaded, and just glancing at the translations was a thing only I would do to compare my progress, but I'm not sure we gained value there.

Anyway the rest of the navigation (topics, and esp. names) has always been a thing of beauty so I might not be the best interface designer :)

Thanks again, cheers, and happy 2016!

**Comment by QilessQi** [comment]
Yes, I struggled with the index page changes too.  There were benefits I really wanted from the DataTables widget, like the ability to sort by geekiness, and length (soon), and search interactively.  But the matrix of languages was just too wide to work well with the contents page anymore, and it was getting pretty sparse.

However, I can make the "classic" index page an option for those that preferred it.  And perhaps there's a compromise where I can make the language choices more "visible" in the individual cases.

I do like adding the "Translations" as text up top... I'll need to fiddle with the site layout so things don't wrap in an ugly way, especially for languages like Russian where words take up more horizontal space.

**Comment by QilessQi** [comment]
Merged #413

**Comment by abelards** [comment]
How about:
- getting the lang as a filter even if it has no column (or a custom label?)
- show 50 entries by default so it doesn't feel too big nor too small?

Thanks again for all the cases of course, I am still a huge fan <3

**Pull request merged**
