### PR TITLE
Spellcheck for the existing Polish translations

### PR DESCRIPTION
**Pull request by tehora**

### CODE REVIEW

**Comment by krzysztof-sikorski** [comment]
:+1: *foka aprobaty* ;)

**Comment by QilessQi** [comment]
I will trust the "Seal of Approval" then.  :-)   Merged #387

**Comment by krzysztof-sikorski** [comment]
@QilessQi I do hope you realised that "*foka aprobaty*" is definitely **not** a
[correct translation](https://en.wikipedia.org/wiki/Homonym) :smiley:

**Comment by QilessQi** [comment]
Well, I do now!

**Pull request merged**
