### PR TITLE
[pt] Case 169

### PR DESCRIPTION
**Pull request by lucasrodcosta**
My first contribution to The Codeless Code.

### CODE REVIEW

**Comment by QilessQi** [comment]
Hi, Lucas!  Thanks for your pull request...  let me review tonight to make sure that you're set up properly as a translator.  :-)

**Comment by QilessQi** [comment]
Case #352

**Comment by QilessQi** [comment]
Many thanks, Lucas!  Your translation is up:
http://thecodelesscode.com/case/169?lang=pt&trans=lucasrodcosta

**Comment by lucasrodcosta** [comment]
\o/
Thanks Qi!
I'm proud to help you in the Codeless Code project!
I'll translate other texts soon. :-)

**Pull request merged**
