### PR TITLE
Matisse quote.

### PR DESCRIPTION
**Pull request by abelards**
Suggesting a fix to the master himself: if this is a Matisse quote, the painting said "Ceci n'est pas une pipe", so I suggest "Ceci n'est pas une peinture." Cheers!

### CODE REVIEW

**Comment by QilessQi** [comment]
It that legitimate French?  If so, I'm very happy to make the change.  :-)

Regards,

Qi

**Comment by abelards** [comment]
Yes it is the legitimate French for "this is not a painting" ^_^
Cheers,

**Comment by cdlm** [comment]
I think "ceci n'est pas…" would translate to "this here is not…" with an explicit designation of the subject.
In contrast, "ce n'est pas…" is more expeditive, and makes reference to previous context, as in "that's not a painting".

**Comment by alessandro1997** [comment]
@QilessQi Should I merge this then?

**Comment by QilessQi** [comment]
I already made the suggested change in the main copy, so feel free to merge
it if that won't create a problem .  :-)

**Comment by alessandro1997** [comment]
Oh, okay, I'm closing this then. :)

**Pull request closed without merging**
