### PR TITLE
Case 173 - FR - Pair Perdu

### PR DESCRIPTION
**Pull request by abelards**
WE DID IT \o/

It's all alexandrine, rhyming ABBA with 12 syllables, and a split at 6/6 which never cuts a word and sometimes rhyme.
I added two footnotes, and a Translator's comment with a joke full of french double-entendre and OSI model.
Rubix and Catwell's review were invaluable to me, thanks guys.

So I actually liked the challenge, and boy did you deliver!
Kudos to Andre Bogus, who gave me the courage to step up.

My translator's note translates to:
    Love follows a rule that's in reverse order from OSI:
     we do our best (FR pun with application),
     we get introduced (FR pun with presentation),
     we communicate between hosts ;
     when come the raptures (FR pun with transportation) of love,
     we try to keep control to direct in safe harbour (FR pun with port) ;
     then we go all out (FR pun with packets) so there's an affair (liaison)
     and, perhaps, become physical.

### CODE REVIEW

**Comment by abelards** [comment]
Weird that GitHub can't resolve conflicts, if you find out what I did wrong please tell me.
Cheers,

**Comment by QilessQi** [comment]
That is pretty awesome!  I'm looking forward to reading it, or at least,
having my lady read it to me, since she speaks French.  :-)

Alessandro is taking a well-deserved vacation right now, so I will have to
look at it this evening when I return from work.  In the meanwhile, if you
don't have the ability to resolve the conflicts, you can send me the
intended final form of the file by email and I'll resolve the conflicts on
the main branch.  :-)

Many, many thanks for your hard work!

Qi

**Comment by alessandro1997** [comment]
The case number is 173, not 178. If you rename the file accordingly, automatic merging should work.

**Comment by abelards** [comment]
Done (and I'm happy to report it's painlessly doable in the Web UI).
Sorry for the mess and thanks for the diagnostic!

**Comment by alessandro1997** [comment]
Merged.

Congratulations! I myself am still looking for the courage needed to translate this one. :smile:

**Comment by abelards** [comment]
Well, when I noticed it had a german translation I opened up my editor.
I did roughly a stanza a day: 4 lines is something you can fit in your day without getting exhausted (perhaps not for you since you're already checking and merging everyone's work... thanks so much!)
Then a few re-readings by friends helped a lot.
Good luck!

**Pull request merged**
