### PR TITLE
Case 193 - FR - Le Cercle Vicieux

### PR DESCRIPTION
**Pull request by abelards**

### CODE REVIEW

**Comment by abelards** [comment]
**Warning: (very weak) feminist debate follows.**
*Disclaimer: I'm a white male, organises RailsGirls Paris, and read a bit on the topic, but that's all.*

I must say that The Codeless Code has a few strong female characters and I think is quite equalitarian in this respect, in the other cases. But I found a few disturbing things about this case.

*First, some feminists frown upon the use of the word "girls".*
I translated all occurences as "sisters".
Since a few monks are called "boy" that might be OK but most monks are just "men", so why not just women or sisters?

*Second, doing what one loves is a very privileged way of thinking.*
I suppose the setup (poor family) acknowledges this, and masters (if not abbots) would laugh at education, schools and degrees.

But there are many jobs a non-coder can do, and I guess Master Suku would just throw questions (or [#159|blocks]) at them, or see whether they have some sense in communication and constraints (and dodging things, a useful skill at the Temple), in which case the sisters would be a perfect fit for the head abbot to solve his recurring lack of abbots (cases 61, 62, 67, 104, 120, 179).

I would very much love to write a case on this topic: what is asked from abbots and how non-coders can be perfect managers. Feel free to write one but I'll add this to my idea list :)

Cheers,

**Comment by QilessQi** [comment]
Not a problem: my lady and I both self-label as "feminist", and I am always
on the lookout for instances of gender bias in my own code.  (Also, I have
recently taught Java coding for "Girl Develop It", so we are very similar
in that regard. :-) )

The funny thing about this case is, the original draft was "brothers" and
"boys", and I imagined them being in their mid-teens... I simply flipped
the words to the direct equivalents of "sisters" and "girls" because the
last two cases involved an all-male cast.  :-)    I imagine the Temple as
being an odd cross between a school and a business, where the monks and
nuns are functionally apprentices, so one might expect novices to apply
when reasonably young.  I think I have used "boy" quite a lot when
referring to novice monks.

As for "doing what one loves", note that Kaimu did not say, "do what you
love as your profession", which I agree would have been highly
over-simplistic.  He advised them to do what they must to survive, so that
in their *spare* time they can do what they truly love.  This is what many
of my friends do... by day they are paid office workers or carpenters or
bus drivers, so that by night they can be unpaid performers or musicians or
writers.

Although the Temple educates its monks and nuns, it has standards like any
business/university, and it does not simply take *anyone.  *Either the
applicant must be useful to the Temple immediately, or they must
demonstrate the clear potential to be useful in the future.  We do this at
my current customer site.  We sometimes hire fresh-outs with very little
relevant experience -- sometimes even with no experience -- but those
fresh-outs must demonstrate their *potential *to us.

This is what Kaimu is after.  He is looking to see which of these
unqualified sisters will continue to code simply because it is their
*passion*; because it is something they *truly *love.  When the third
sister shows this potential, Kaimu recommends that she be hired.  Not
because she has acquired experience, but because she has demonstrated that
she has this passion.  Experience may be acquired by anyone with a little
luck and a little skill.  Passion comes only from within.

(By the way, I think the masters would respect education and degrees, but
not all schools are worthy of high respect, and I *always* give a coding
interview regardless.  I will gladly accept a skilled developer from a bad
school before a poor developer from a good school.)

Perhaps I should make it clearer that the sisters are in fact unqualified
to be admitted... what about this:

*“I cannot hire any of you,” said the abbot after he looked at their
résumés and the results of their coding exams. “You do not have the
necessary experience.”*

What do you think?

Qi

**Comment by abelards** [comment]
I don't mean to force changes upon you, and the case was nice anyway :)
I just wanted to point at the dangers of any overly simplistic approaches but, well, you wrote more than 193 cases on avoiding that!

I did notice the use of "boy" and perhaps I wouldn't have been surprised at the word "girls" if any mention of their age explained it: `young sisters` or `as novice developers`. In real life, not anyone reaches the point of having code exams as it's already a significant time investment. Perhaps code samples?

Cheers again :)

PS: I re-read many cases, did you add images for some? I didn't recall so many had them.

**Comment by QilessQi** [comment]
I have no problem with fine-tuning cases if it helps get the intended
meaning across... I think of it as necessary refactoring.  :-)  I do like
clarifying that the girls are young, and that the abbot at least looked at
their code and not just their resumes.

And yes, I have been adding some illustrations late.  Often when it's late
it's just a day late, but sometimes I do go back and illustrate cases that
were previously lacking pictures.  It's good practice for me.  :-)

Many regards,

Qi

**Pull request merged**
