### PR TITLE
Case 191 - FR - Les Quatre Mots de la Détresse

### PR DESCRIPTION
**Pull request by abelards**
I now realise that in French Cancel and Undo are the same word Annuler. Oh my.

### CODE REVIEW

**Comment by QilessQi** [comment]
Intriguing!  I think you will have to change it to the "Three Words..."
then. :-)

**Comment by abelards** [comment]
I kept the "Four words" and used "Annuler" for _Cancel_ but I used "Go a step back" for _Undo_ :)
I'm still organising my thoughts on this. Deeper than I'd thought.

**Comment by QilessQi** [comment]
This piece only scratches the surface of the ideas that I want to talk
about; I expect that the next case will be a "Part 2" for this topic.
There's a lot to be said on the subject of "user-error recovery", and the
subtle differences between the different mechanisms discussed here, both
from a user point-of-view and a developer point-of-view.

**Comment by alessandro1997** [comment]
@abelards is this good to merge or are you still choosing a title? :smile:

**Comment by abelards** [comment]
@alessandro1997 no the title is good, I just translated the single word UNDO in "take a step back".

@QilessQi I was just writing a case with a young french scribe coming to ask you questions -- but can't find a good enough metaphor :)

**Pull request merged**
