### PR TITLE
Case 96 - FR - sans état

### PR DESCRIPTION
**Pull request by abelards**

### CODE REVIEW

**Comment by alessandro1997** [comment]
The file lacks the "Lang" and "Translator" tags. Would you mind adding them?

**Comment by abelards** [comment]
Done, sorry. Sharp eyes!

**Comment by alessandro1997** [comment]
Eh, I've checked hundreds of cases so I don't even think about it anymore. :joy:

**Comment by abelards** [comment]
Yes, it's pretty awesome because when I started I don't remember seeing as many translations, esp ES, PL and DE. FR will soon be almost up to date!

**Comment by QilessQi** [comment]
You folks are pretty awesome.  :-)

Regards,

Qi

**Pull request merged**
