### PR TITLE
Cases 1 to 29 - CS

### PR DESCRIPTION
**Pull request by Hanzik**
Hi there, this is my first attempt to contribute to The Codeless Code - 29 koans translated to Czech language. 

If there is something to be fixed, let me know and I will look into it.

Cheers!

### CODE REVIEW

**Comment by krzysztof-sikorski** [comment]
It would be nice if you also added an `extras/about-translator.txt` file.

See issue #260 for discussion and translations `fr-abelards`, `fr-cdlm`, `it-alessandro1997` or `pl-badziew` for syntax examples.

**Comment by Hanzik** [comment]
I will look into it. Thanks.

**Comment by QilessQi** [comment]
Merged... many thanks, Hanzik!  You should see your changes on the website within a day.

**Comment by Hanzik** [comment]
Thanks a lot. I will try to translate your work on a more regular basis, but I would rather not promise anything... the 'translating fever' comes only ever so often. :)

**Pull request merged**
