### PR TITLE
Merge pull request #29 from alessandro1997/master

### PR DESCRIPTION
**Pull request by galcalde**
update

### CODE REVIEW

**Comment by cdlm** [comment]
I don't understand, aren't those commits already merged here ?

**Comment by galcalde** [comment]
It's just an automatic commit that github creates when you update your repository

**Comment by cdlm** [comment]
I'm still confused, it never happened to me before… how do you update your repo ?

**Comment by galcalde** [comment]
when you make a pull request, you click on the link "switching base" and it shows all the commits that are on the other repo that haven't been commited on your repo. There you make a pull request to include all these commits on your repo.

**Pull request closed without merging**
